spring:
  application:
    name: spring-boot-with-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_with_java?useTimezone=true&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      show_sql: false
    open-in-view: false
logging:
  level:
    root: INFO
    #br.com.thiagodotjpeg: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
