name: Continuos Integration and Delivery with Github Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build application .jar
        working-directory: ./spring-boot-with-java
        run: mvn clean package

      - name: Docker compose Build
        working-directory: ./spring-boot-with-java
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/spring_boot_with_java:latest ${{ secrets.DOCKER_USERNAME }}/spring_boot_with_java:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/spring_boot_with_java:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/spring_boot_with_java:${{ github.run_id }}
          
